import type { NextApiRequest, NextApiResponse } from "next";
import { CitiesProps } from "../../types/Cards100";

interface ResponseProps {
  continent: string | string[];
  quantity: number;
  cities: CitiesProps[];
}

export default function handler(
  req: NextApiRequest,
  res: NextApiResponse<ResponseProps>
) {
  const data: CitiesProps[] = [
    {
      id: "1",
      name: "Hong Kong",
      country: "China",
      flag: "https://flagcdn.com/w320/cn.png",
      city_img: "",
      continent: "Ásia",
    },
    {
      id: "2",
      name: "Bangkok",
      country: "Tailândia",
      flag: "https://flagcdn.com/w320/th.png",
      city_img: "",
      continent: "Ásia",
    },
    {
      id: "3",
      name: "London",
      country: "Reino Unido",
      flag: "https://flagcdn.com/w320/gb.png",
      city_img: "",
      continent: "Europa",
    },
    {
      id: "4",
      name: "Macau",
      country: "China",
      flag: "https://flagcdn.com/w320/cn.png",
      city_img: "",
      continent: "Ásia",
    },
    {
      id: "5",
      name: "Singapura",
      country: "Singapura",
      flag: "https://flagcdn.com/w320/sg.png",
      city_img: "",
      continent: "Ásia",
    },
    {
      id: "6",
      name: "Paris",
      country: "França",
      flag: "https://flagcdn.com/w320/fr.png",
      city_img: "",
      continent: "Europa",
    },
    {
      id: "7",
      name: "Dubai",
      country: "Emirados Árabes",
      flag: "https://flagcdn.com/w320/ae.png",
      city_img: "",
      continent: "Ásia",
    },
    {
      id: "8",
      name: "New York City",
      country: "Estados Unidos",
      flag: "https://flagcdn.com/w320/us.png",
      city_img: "",
      continent: "America do Norte",
    },
    {
      id: "9",
      name: "Kuala Lumpur",
      country: "MalÁsia",
      flag: "https://flagcdn.com/w320/my.png",
      city_img: "",
      continent: "Ásia",
    },
    {
      id: "10",
      name: "Istambul",
      country: "Turquia",
      flag: "https://flagcdn.com/w320/tr.png",
      city_img: "",
      continent: "Europa",
    },
    {
      id: "11",
      name: "Delhi",
      country: "India",
      flag: "https://flagcdn.com/w320/in.png",
      city_img: "",
      continent: "Ásia",
    },
    {
      id: "12",
      name: "Antalya",
      country: "Turquia",
      flag: "https://flagcdn.com/w320/tr.png",
      city_img: "",
      continent: "Europa",
    },
    {
      id: "13",
      name: "Shenzhen",
      country: "China",
      flag: "https://flagcdn.com/w320/cn.png",
      city_img: "",
      continent: "Ásia",
    },
    {
      id: "14",
      name: "Mumbai",
      country: "India",
      flag: "https://flagcdn.com/w320/in.png",
      city_img: "",
      continent: "Ásia",
    },
    {
      id: "15",
      name: "Phuket",
      country: "Tailândia",
      flag: "https://flagcdn.com/w320/th.png",
      city_img: "",
      continent: "Ásia",
    },
    {
      id: "16",
      name: "Rome",
      country: "Italia",
      flag: "https://flagcdn.com/w320/it.png",
      city_img: "",
      continent: "Europa",
    },
    {
      id: "17",
      name: "Tokyo",
      country: "Japão",
      flag: "https://flagcdn.com/w320/jp.png",
      city_img: "",
      continent: "Ásia",
    },
    {
      id: "18",
      name: "Pattaya",
      country: "Tailândia",
      flag: "https://flagcdn.com/w320/th.png",
      city_img: "",
      continent: "Ásia",
    },
    {
      id: "19",
      name: "Taiwan",
      country: "China",
      flag: "https://flagcdn.com/w320/cn.png",
      city_img: "",
      continent: "Ásia",
    },
    {
      id: "20",
      name: "Mecca",
      country: "Arábia Saudita",
      flag: "https://flagcdn.com/w320/ae.png",
      city_img: "",
      continent: "Ásia",
    },
    {
      id: "21",
      name: "Guangzhou",
      country: "China",
      flag: "https://flagcdn.com/w320/cn.png",
      city_img: "",
      continent: "Ásia",
    },
    {
      id: "22",
      name: "Prague",
      country: "Republica Tcheca",
      flag: "https://flagcdn.com/w320/cz.png",
      city_img: "",
      continent: "Europa",
    },
    {
      id: "23",
      name: "Medina",
      country: "Arábia Saudita",
      flag: "https://flagcdn.com/w320/ae.png",
      city_img: "",
      continent: "Ásia",
    },
    {
      id: "24",
      name: "Seoul",
      country: "Coreia do Sul",
      flag: "https://flagcdn.com/w320/kr.png",
      city_img: "",
      continent: "Ásia",
    },
    {
      id: "25",
      name: "Amsterdam",
      country: "Holanda",
      flag: "https://flagcdn.com/w320/nl.png",
      city_img: "",
      continent: "Europa",
    },
    {
      id: "26",
      name: "Agra",
      country: "India",
      flag: "https://flagcdn.com/w320/in.png",
      city_img: "",
      continent: "Ásia",
    },
    {
      id: "27",
      name: "Miami",
      country: "Estados Unidos",
      flag: "https://flagcdn.com/w320/us.png",
      city_img: "",
      continent: "America do Norte",
    },
    {
      id: "28",
      name: "Osaka",
      country: "Japão",
      flag: "https://flagcdn.com/w320/jp.png",
      city_img: "",
      continent: "Ásia",
    },
    {
      id: "29",
      name: "Los Angeles",
      country: "Estados Unidos",
      flag: "https://flagcdn.com/w320/us.png",
      city_img: "",
      continent: "America do Norte",
    },
    {
      id: "30",
      name: "Shanghai",
      country: "China",
      flag: "https://flagcdn.com/w320/cn.png",
      city_img: "",
      continent: "Ásia",
    },
    {
      id: "31",
      name: "Ho Chi Minh City",
      country: "Vietnã",
      flag: "https://flagcdn.com/w320/vn.png",
      city_img: "",
      continent: "Ásia",
    },
    {
      id: "32",
      name: "Denpasar",
      country: "Indonesia",
      flag: "https://flagcdn.com/w320/id.png",
      city_img: "",
      continent: "Ásia",
    },
    {
      id: "33",
      name: "Barcelona",
      country: "Espanha",
      flag: "https://flagcdn.com/w320/es.png",
      city_img: "",
      continent: "Europa",
    },
    {
      id: "34",
      name: "Las Vegas",
      country: "Estados Unidos",
      flag: "https://flagcdn.com/w320/us.png",
      city_img: "",
      continent: "America do Norte",
    },
    {
      id: "35",
      name: "Milan",
      country: "Italia",
      flag: "https://flagcdn.com/w320/it.png",
      city_img: "",
      continent: "Europa",
    },
    {
      id: "36",
      name: "Chennai",
      country: "India",
      flag: "https://flagcdn.com/w320/in.png",
      city_img: "",
      continent: "Ásia",
    },
    {
      id: "37",
      name: "Vienna",
      country: "Austria",
      flag: "https://flagcdn.com/w320/at.png",
      city_img: "",
      continent: "Europa",
    },
    {
      id: "38",
      name: "Johor Bahru",
      country: "MalÁsia",
      flag: "https://flagcdn.com/w320/my.png",
      city_img: "",
      continent: "Ásia",
    },
    {
      id: "39",
      name: "Jaipur",
      country: "India",
      flag: "https://flagcdn.com/w320/in.png",
      city_img: "",
      continent: "Ásia",
    },
    {
      id: "40",
      name: "Cancun",
      country: "Mexico",
      flag: "https://flagcdn.com/w320/mx.png",
      city_img: "",
      continent: "America do Norte",
    },
    {
      id: "41",
      name: "Berlim",
      country: "Alemanha",
      flag: "https://flagcdn.com/w320/de.png",
      city_img: "",
      continent: "Europa",
    },
    {
      id: "42",
      name: "Cairo",
      country: "Egito",
      flag: "https://flagcdn.com/w320/eg.png",
      city_img: "",
      continent: "África",
    },
    {
      id: "43",
      name: "Atenas",
      country: "Grecia",
      flag: "https://flagcdn.com/w320/gr.png",
      city_img: "",
      continent: "Europa",
    },
    {
      id: "44",
      name: "Orlando",
      country: "Estados Unidos",
      flag: "https://flagcdn.com/w320/us.png",
      city_img: "",
      continent: "America do Norte",
    },
    {
      id: "45",
      name: "Moscou",
      country: "Russia",
      flag: "https://flagcdn.com/w320/ru.png",
      city_img: "",
      continent: "Ásia",
    },
    {
      id: "46",
      name: "Venice",
      country: "Italia",
      flag: "https://flagcdn.com/w320/it.png",
      city_img: "",
      continent: "Europa",
    },
    {
      id: "47",
      name: "Madrid",
      country: "Espanha",
      flag: "https://flagcdn.com/w320/es.png",
      city_img: "",
      continent: "Europa",
    },
    {
      id: "48",
      name: "Ha Long",
      country: "Vietnã",
      flag: "https://flagcdn.com/w320/vn.png",
      city_img: "",
      continent: "Ásia",
    },
    {
      id: "49",
      name: "Riyadh",
      country: "Arábia Saudita",
      flag: "https://flagcdn.com/w320/ae.png",
      city_img: "",
      continent: "Ásia",
    },
    {
      id: "50",
      name: "Dublin",
      country: "Irlanda",
      flag: "https://flagcdn.com/w320/ie.png",
      city_img: "",
      continent: "Europa",
    },
    {
      id: "51",
      name: "Florence",
      country: "Italia",
      flag: "https://flagcdn.com/w320/it.png",
      city_img: "",
      continent: "Europa",
    },
    {
      id: "52",
      name: "Ha Noi",
      country: "Vietnã",
      flag: "https://flagcdn.com/w320/vn.png",
      city_img: "",
      continent: "Ásia",
    },
    {
      id: "53",
      name: "Toronto",
      country: "Canadá",
      flag: "https://flagcdn.com/w320/ca.png",
      city_img: "",
      continent: "America do Norte",
    },
    {
      id: "54",
      name: "Johannesburg",
      country: "Africa do Sul",
      flag: "https://flagcdn.com/w320/za.png",
      city_img: "",
      continent: "África",
    },
    {
      id: "55",
      name: "Sidney",
      country: "Austrália",
      flag: "https://flagcdn.com/w320/au.png",
      city_img: "",
      continent: "Oceania",
    },
    {
      id: "56",
      name: "Munique",
      country: "Alemanha",
      flag: "https://flagcdn.com/w320/de.png",
      city_img: "",
      continent: "Europa",
    },
    {
      id: "57",
      name: "Jakarta",
      country: "Indonesia",
      flag: "https://flagcdn.com/w320/id.png",
      city_img: "",
      continent: "Ásia",
    },
    {
      id: "58",
      name: "Beijing",
      country: "China",
      flag: "https://flagcdn.com/w320/cn.png",
      city_img: "",
      continent: "Ásia",
    },
    {
      id: "59",
      name: "São Petersburg",
      country: "Russia",
      flag: "https://flagcdn.com/w320/ru.png",
      city_img: "",
      continent: "Ásia",
    },
    {
      id: "60",
      name: "Brussels",
      country: "Bélgica",
      flag: "https://flagcdn.com/w320/be.png",
      city_img: "",
      continent: "Europa",
    },
    {
      id: "61",
      name: "Jerusalem",
      country: "Israel",
      flag: "https://flagcdn.com/w320/il.png",
      city_img: "",
      continent: "Ásia",
    },
    {
      id: "62",
      name: "Budapeste",
      country: "Hungria",
      flag: "https://flagcdn.com/w320/hu.png",
      city_img: "",
      continent: "Europa",
    },
    {
      id: "63",
      name: "Lisboa",
      country: "Portugal",
      flag: "https://flagcdn.com/w320/pt.png",
      city_img: "",
      continent: "Europa",
    },
    {
      id: "64",
      name: "Dammam",
      country: "Arábia Saudita",
      flag: "https://flagcdn.com/w320/ae.png",
      city_img: "",
      continent: "Ásia",
    },
    {
      id: "65",
      name: "Ilha de Penang",
      country: "MalÁsia",
      flag: "https://flagcdn.com/w320/my.png",
      city_img: "",
      continent: "Ásia",
    },
    {
      id: "66",
      name: "Heraklion",
      country: "Grecia",
      flag: "https://flagcdn.com/w320/gr.png",
      city_img: "",
      continent: "Europa",
    },
    {
      id: "67",
      name: "Kyoto",
      country: "Japão",
      flag: "https://flagcdn.com/w320/jp.png",
      city_img: "",
      continent: "Ásia",
    },
    {
      id: "68",
      name: "Zhuhai",
      country: "China",
      flag: "https://flagcdn.com/w320/cn.png",
      city_img: "",
      continent: "Ásia",
    },
    {
      id: "69",
      name: "Vancouver",
      country: "Canadá",
      flag: "https://flagcdn.com/w320/ca.png",
      city_img: "",
      continent: "America do Norte",
    },
    {
      id: "70",
      name: "Chiang Mai",
      country: "Tailândia",
      flag: "https://flagcdn.com/w320/th.png",
      city_img: "",
      continent: "Ásia",
    },
    {
      id: "71",
      name: "Copenhagen",
      country: "Dinamarca",
      flag: "https://flagcdn.com/w320/dk.png",
      city_img: "",
      continent: "Europa",
    },
    {
      id: "72",
      name: "São Francisco",
      country: "Estados Unidos",
      flag: "https://flagcdn.com/w320/us.png",
      city_img: "",
      continent: "America do Norte",
    },
    {
      id: "73",
      name: "Melbourne",
      country: "Austrália",
      flag: "https://flagcdn.com/w320/au.png",
      city_img: "",
      continent: "Oceania",
    },
    {
      id: "74",
      name: "Cracóvia",
      country: "Polônia",
      flag: "https://flagcdn.com/w320/pl.png",
      city_img: "",
      continent: "Europa",
    },
    {
      id: "75",
      name: "Marrakech",
      country: "Marrocos",
      flag: "https://flagcdn.com/w320/ma.png",
      city_img: "",
      continent: "África",
    },
    {
      id: "76",
      name: "Kolkatta",
      country: "India",
      flag: "https://flagcdn.com/w320/in.png",
      city_img: "",
      continent: "Ásia",
    },
    {
      id: "77",
      name: "Cebu",
      country: "Filipinas",
      flag: "https://flagcdn.com/w320/ph.png",
      city_img: "",
      continent: "Ásia",
    },
    {
      id: "78",
      name: "Auckland",
      country: "Nova Zelândia",
      flag: "https://flagcdn.com/w320/nz.png",
      city_img: "",
      continent: "Oceania",
    },
    {
      id: "79",
      name: "Tel Aviv",
      country: "Israel",
      flag: "https://flagcdn.com/w320/il.png",
      city_img: "",
      continent: "Ásia",
    },
    {
      id: "80",
      name: "Guilin",
      country: "China",
      flag: "https://flagcdn.com/w320/cn.png",
      city_img: "",
      continent: "Ásia",
    },
    {
      id: "81",
      name: "Honolulu",
      country: "Estados Unidos",
      flag: "https://flagcdn.com/w320/us.png",
      city_img: "",
      continent: "America do Norte",
    },
    {
      id: "82",
      name: "Hurgada",
      country: "Egito",
      flag: "https://flagcdn.com/w320/eg.png",
      city_img: "",
      continent: "África",
    },
    {
      id: "83",
      name: "Warsaw",
      country: "Polônia",
      flag: "https://flagcdn.com/w320/pl.png",
      city_img: "",
      continent: "Europa",
    },
    {
      id: "84",
      name: "Mugla",
      country: "Turquia",
      flag: "https://flagcdn.com/w320/tr.png",
      city_img: "",
      continent: "Europa",
    },
    {
      id: "85",
      name: "Buenos Aires",
      country: "Argentina",
      flag: "https://flagcdn.com/w320/ar.png",
      city_img:
        "https://veja.abril.com.br/wp-content/uploads/2020/05/gettyimages-1218824829.jpg.jpg",
      continent: "America do Sul",
    },
    {
      id: "86",
      name: "Chiba",
      country: "Japão",
      flag: "https://flagcdn.com/w320/jp.png",
      city_img: "",
      continent: "Ásia",
    },
    {
      id: "87",
      name: "Frankfurt",
      country: "Alemanha",
      flag: "https://flagcdn.com/w320/de.png",
      city_img: "",
      continent: "Europa",
    },
    {
      id: "88",
      name: "Estocolmo",
      country: "Suécia",
      flag: "https://flagcdn.com/w320/se.png",
      city_img: "",
      continent: "Europa",
    },
    {
      id: "89",
      name: "Lima",
      country: "Peru",
      flag: "https://flagcdn.com/w320/pe.png",
      city_img:
        "https://www.peru.travel/Contenido/Atractivo/Imagen/pt/218/1.1/Principal/shutterstock_682350013.jpg",
      continent: "America do Sul",
    },
    {
      id: "90",
      name: "Da Nang",
      country: "Vietnã",
      flag: "https://flagcdn.com/w320/vn.png",
      city_img: "",
      continent: "Ásia",
    },
    {
      id: "91",
      name: "Batam",
      country: "Indonesia",
      flag: "https://flagcdn.com/w320/id.png",
      city_img: "",
      continent: "Ásia",
    },
    {
      id: "92",
      name: "Nice",
      country: "França",
      flag: "https://flagcdn.com/w320/fr.png",
      city_img: "",
      continent: "Europa",
    },
    {
      id: "93",
      name: "Fukuoka",
      country: "Japão",
      flag: "https://flagcdn.com/w320/jp.png",
      city_img: "",
      continent: "Ásia",
    },
    {
      id: "94",
      name: "Abu Dhabi",
      country: "Emirados Árabes",
      flag: "https://flagcdn.com/w320/ae.png",
      city_img: "",
      continent: "Ásia",
    },
    {
      id: "95",
      name: "Jeju",
      country: "Coreia do Sul",
      flag: "https://flagcdn.com/w320/kr.png",
      city_img: "",
      continent: "Ásia",
    },
    {
      id: "96",
      name: "Porto",
      country: "Portugal",
      flag: "https://flagcdn.com/w320/pt.png",
      city_img: "",
      continent: "Europa",
    },
    {
      id: "97",
      name: "Rhodes",
      country: "Grecia",
      flag: "https://flagcdn.com/w320/gr.png",
      city_img: "",
      continent: "Europa",
    },
    {
      id: "98",
      name: "Rio de Janeiro",
      country: "Brasil",
      flag: "https://flagcdn.com/w320/br.png",
      city_img:
        "https://freewalkertours.com/wp-content/uploads/mariano-diaz-7F65HDP0-E0-unsplash-1100x733.jpg",
      continent: "America do Sul",
    },
    {
      id: "99",
      name: "Krabi",
      country: "Tailândia",
      flag: "https://flagcdn.com/w320/th.png",
      city_img: "",
      continent: "Ásia",
    },
    {
      id: "100",
      name: "Bangalore",
      country: "India",
      flag: "https://flagcdn.com/w320/in.png",
      city_img: "",
      continent: "Ásia",
    },
  ];

  const continent: string | string[] = req.query.continent;

  const response: CitiesProps[] = data.filter((city) => {
    return city.continent.toLowerCase() == continent;
  });

  res.status(200).json({
    continent,
    quantity: response.length,
    cities: response,
  });
}
